Also disable datagen part of CI verify - it's broken and not worth fixing right now.

diff --git a/.github/workflows/verify.yml b/.github/workflows/verify.yml
--- a/.github/workflows/verify.yml
+++ b/.github/workflows/verify.yml
@@ -24,22 +24,23 @@ jobs:
         uses: gradle/gradle-build-action@v2
         with:
           arguments: build
-      - name: Run data generator
-        uses: gradle/gradle-build-action@v2
-        with:
-          arguments: runData
-      - name: Check data generated successfully # So we do this to ensure something was done, .cache will always be written
-        id: check_files
-        uses: andstor/file-existence-action@v1
-        with:
-          files: "src/generated/resources/.cache/"
-      - name: Remove generation cache for comparison
-        run: rm -rf src/generated/resources/.cache
-      - name: Compare generated resources
-        run: |
-          diff -r --strip-trailing-cr --ignore-blank-lines generatedBak src/generated
-          if [ $? -ne 0 ]; then
-              echo "Mismatch between generated data and committed data, please re-run runDataProd and push those changes.";
-              exit 1;
-          fi
-          echo "Passed data check";
+      # Disabled the datagen step due to continuous fails by JSON orderings.
+#      - name: Run data generator
+#        uses: gradle/gradle-build-action@v2
+#        with:
+#          arguments: runData
+#      - name: Check data generated successfully # So we do this to ensure something was done, .cache will always be written
+#        id: check_files
+#        uses: andstor/file-existence-action@v1
+#        with:
+#          files: "src/generated/resources/.cache/"
+#      - name: Remove generation cache for comparison
+#        run: rm -rf src/generated/resources/.cache
+#      - name: Compare generated resources
+#        run: |
+#          diff -r --strip-trailing-cr --ignore-blank-lines generatedBak src/generated
+#          if [ $? -ne 0 ]; then
+#              echo "Mismatch between generated data and committed data, please re-run runDataProd and push those changes.";
+#              exit 1;
+#          fi
+#          echo "Passed data check";
